### PR TITLE
Django 2.0+ support

### PR DESCRIPTION
**Pull request by RankoR**
Added Django 2.0 support, keeping older versions. All tests passed.

### CODE REVIEW

**Comment by MikeSandford** [comment]
I got it working on my local machine with fewer changes than this, so this looks pretty thorough to me.  Thanks for doing this!

Most of the build errors look like this:
```
 make test
flake8
./field_history/json_nested_serializer.py:26:5: C901 'Serializer.serialize' is too complex (13)
./tests/tests.py:16:1: E402 module level import not at top of file
./tests/tests.py:17:1: E402 module level import not at top of file
./tests/tests.py:19:1: E402 module level import not at top of file
./tests/urls.py:1:1: F401 'django.conf.urls.include' imported but unused
make: *** [lint] Error 1
```

A couple of them look like this:
```
$ make test
flake8
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.2.6/bin/flake8", line 7, in <module>
    from flake8.main.cli import main
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/flake8/main/cli.py", line 2, in <module>
    from flake8.main import application
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/flake8/main/application.py", line 15, in <module>
    from flake8.options import aggregator, config
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/flake8/options/aggregator.py", line 8, in <module>
    from flake8.options import config
  File "/home/travis/virtualenv/python3.2.6/lib/python3.2/site-packages/flake8/options/config.py", line 63
    if isinstance(files, (str, type(u''))):
                                      ^
SyntaxError: invalid syntax
make: *** [lint] Error 1
```

**Comment by mscansian** [comment]
I endorse @MikeSandford words. These are all linter errors, because the lib has to do some "clever magic" to keep compatibility with Django 1.7 through 2.1.

I think we should just drop support for older Django versions and deal only with Django 1.11 and Django 2.x. Just a reminder that [Django 1.10 has reached the EOL more than 6 months ago](https://www.djangoproject.com/weblog/2015/jun/25/roadmap/).

**Comment by grantmcconnaughey** [comment]
I'm totally on board with removing compatibility with Django 1.7-1.10 and only supporting the Python versions that Django 1.11-2.1 supports.

**Comment by grantmcconnaughey** [comment]
Fixed in #28

**Pull request closed without merging**
