### PR TITLE
Avoid adding new tracking object for already tracked fields

### LINKED ISSUE #8: `createinitialfieldhistory` creates initial value even for already tracking objects
I need to run ```python manage.py createinitialfieldhistory``` inside provision script during launch, so every time I deploy it creates new values for already tracked fields, which I don't think is necessary.

Is it possible for this command to omit already tracked objects? Thanks.

### PR DESCRIPTION
**Pull request by mariodev**
Resolves #8

### CODE REVIEW

**Comment by grantmcconnaughey** [comment]
Hey, thanks for the PR! I like this idea. I think I see a bug, however. This part:

```python
if not FieldHistory.objects.filter(object_id=obj.id, field_name=field).exists():
    # etc.
```

Should be this:
```python
content_type = ContentType.objects.get_for_model(obj)
if not FieldHistory.objects.filter(object_id=obj.id, content_type=content_type, field_name=field).exists():
    # etc.
```

That's because `object` is a `GenericForeignKey`, so you have to query for object id _and_ content type.

**Comment by grantmcconnaughey** [comment]
Write a test that fixes that bug, fix the bug, and I'll get it merged soon. Thanks again!

**Comment by mariodev** [comment]
@grantmcconnaughey Added necessary fixes. Thanks for your help!

**Comment by grantmcconnaughey** [comment]
Awesome stuff, @mariodev. Thanks a lot. 👍

**Pull request merged**
